- name: Check if /etc/yum.repos.d/CentOS-Base.repo exists | Qcloud
  stat: path=/etc/yum.repos.d/CentOS-Base.repo
  register: base_repo

- name: Check if /etc/yum.repos.d/CentOS-Epel.repo exists | Qcloud
  stat: path=/etc/yum.repos.d/CentOS-Epel.repo
  register: epel_repo

- name: Backup /etc/yum.repos.d/CentOS-Base.repo | Qcloud
  shell: mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repobak
  when: base_repo.stat.exists

- name: Backup /etc/yum.repos.d/CentOS-Epel.repo | Qcloud
  shell: mv /etc/yum.repos.d/CentOS-Epel.repo /etc/yum.repos.d/CentOS-Epel.repobak
  when: epel_repo.stat.exists

# - name: Clean yum cache | Qcloud
#   shell: yum clean all

- name: Enable community yum base repository | Qcloud
  yum_repository:
    name: centos
    file: centos
    description: CentOS-$releasever - Base
    baseurl: http://mirror.centos.org/centos/$releasever/os/$basearch/
    gpgcheck: no
    state: present

- name: Enable community yum updates repository | Qcloud
  yum_repository:
    name: updates
    file: centos
    description: CentOS-$releasever - Updates
    baseurl: http://mirror.centos.org/centos/$releasever/updates/$basearch/
    gpgcheck: no
    state: present