---

- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: Get certificate key from master
  set_fact:
    kubeadm_certificate_key: "{{ hostvars[groups['master'][0]]['kubeadm_certificate_key'] }}"
  when:
  - kube_version is version('v1.15.0', '>=')

- name: Join to Kubernetes cluster
  when: reset_cluster is succeeded
  shell: |
    kubeadm join --token {{ token }} \
                --discovery-token-unsafe-skip-ca-verification \
                {% if kube_version is version('v1.15.0', '>=') and kubeadm_certificate_key is defined %}
                --certificate-key {{ kubeadm_certificate_key }} \
                {% endif %}
                {{ master_ip }}:6443
  register: join_cluster
  notify:
    - Recreate kube-dns
