---

- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: Get certificate key from master
  set_fact:
    kubeadm_certificate_key: "{{ hostvars[groups['master'][0]]['kubeadm_certificate_key'] }}"

- name: Create kubeadm join config
  template:
    src: "kubeadm-join.j2"
    dest: "{{ kube_config_dir }}/kubeadm-join.yaml"

- name: Wait for k8s apiserver
  wait_for:
    host: "{{ master_ip }}"
    port: "6443"
    timeout: 300

- name: Join control plane to Kubernetes cluster
  when: reset_cluster is succeeded
  shell: |
    kubeadm join --token {{ token }} \
                --discovery-token-unsafe-skip-ca-verification \
                --control-plane \
                --certificate-key {{ kubeadm_certificate_key }} \
                {{ master_ip }}:6443
  # shell: |
  #   kubeadm join --config {{ kube_config_dir }}/kubeadm-join.yaml \
  #                --control-plane
  register: join_cluster
  notify:
    - Recreate kube-dns