---
- name: gets the kubeadm version
  command: "kubeadm version -o short"
  register: kubeadm_output

- name: sets kubeadm api version to v1beta1
  set_fact:
    kubeadmConfig_api_version: v1beta1
  when: kubeadm_output.stdout is version('v1.13.0', '>=')

- name: sets kubeadm api version to v1beta2
  set_fact:
    kubeadmConfig_api_version: v1beta2
  when: kubeadm_output.stdout is version('v1.15.0', '>=')