---

- name: Check if kubeadm has already run
  stat:
    path: "{{ kube_cert_dir }}/ca.key"
  register: kubeadm_ca

- name: Set kubeadm version
  include_tasks: kubeadm-version.yml

- name: Init cluster if needed
  include_tasks: init.yml
  when:
  - inventory_hostname == groups['master']|first
  - not kubeadm_ca.stat.exists
  run_once: yes

- name: Upload kubeadm certificate key
  command: kubeadm init phase --config {{ kube_config_dir }}/kubeadm-config.yaml upload-certs --upload-certs
  register: kubeadm_upload_cert
  when:
  - kube_version is version('v1.15.0', '>=')
  - inventory_hostname == groups['master']|first
  - kubeadm_certificate_key is not defined

- name: Parse kubeadm certificate key if not set
  set_fact:
    kubeadm_certificate_key: "{{ kubeadm_upload_cert.stdout_lines[-1] | trim }}"
  run_once: yes
  when:
  - inventory_hostname == groups['master']|first
  - kubeadm_certificate_key is not defined
  - kubeadm_upload_cert is defined
  - kubeadm_upload_cert is not skipped

- name: Join other control plane master
  include_tasks: join.yml
  when:
  - kube_version is version('v1.15.0', '>=')
  - inventory_hostname != groups['master']|first
  - not kubeadm_ca.stat.exists

- name: Join other control plane master using legacy method
  include_tasks: join-legacy.yml
  when:
  - kube_version is version('v1.15.0', '<')
  - inventory_hostname != groups['master']|first
  - not kubeadm_ca.stat.exists

- name: Enable and check kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
  register: started_kubelet

- name: "Copy config file"
  fetch:
    src: "{{ kubeadmin_config }}"
    dest: "{{ lookup('env', 'HOME') }}/admin.conf"
    flat: yes
  run_once: yes
  ignore_errors: yes
  when: inventory_hostname == groups['master']|first

